version: '3'

services:
  api:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    command: npm run dev
    environment:
      - DB_HOST_DEVELOPMENT=postgres
  db:
      build:
        context: .
        dockerfile: Dockerfile-Postgres
      hostname: postgres
      ports:
          - "5432:5432"
      environment:
            POSTGRES_USER: clip
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: clip
      volumes:
            - ./pg_data:/var/lib/postgresql